# Generated by Django 3.1.4 on 2020-12-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vb_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('psw', models.CharField(max_length=16)),
                ('conf_paw', models.CharField(max_length=16)),
            ],
        ),
    ]
